# Generated by Django 3.2 on 2021-05-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('albums', models.URLField()),
                ('tracks', models.URLField()),
                ('Self', models.URLField()),
            ],
        ),
    ]
